[book]
authors = ["Tarrence van As", "Loaf", "Sylve Chevet", "Sensei"]
language = "en"
multilingual = false
src = "src"
title = "Dojo: The Provable Game Engine"

[build]
extra-watch-dirs = ["po"]

[preprocessor.gettext]
after = ["links"]

[output.html]
git-repository-url = "https://github.com/dojoengine/book"
edit-url-template = "https://github.com/dojoengine/book/edit/main/{path}"
no-section-label = true

[output.html.fold]
enable = true
level = 0
